project_id = "sdnjbzmyayapmseipcvw"

[functions.submit-proposal]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.send-status-email]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.track-email-open]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
